name: Elixir CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.2.8]
        elixir: [1.10.1]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Install Dependencies
      run: mix deps.get

    - name: Assure Codebase is Formatted
      run: mix format --check-formatted

    - name: Run Tests
      run: mix test
